### ISSUE TITLE
Unable to log into "old" Accounts on Testserver

### ISSUE THREAD

**Issue by ThunderNikk** [NGemity/RZEmulator#25] opened 2018-07-23 23:09 UTC
### Version

Current with boost 2018 07 23

### Expected Behaviour 

Account logs in to server selection when ID and Password is accepted by auth

### Actual Behaviour

Account sticks on connecting (left it there for more then 1 hour)

### Steps to reproduce the behaviour

Log in to an older account

### Additional information

New account needs to be created in order to log in

**Comment by Xijezu** [comment] 2018-07-24 05:10
Cannot reproduce it locally (importing the server database and changing your or @XavierDeFawks password to mine for logging in), but can reproduce it remotely (used @XavierDeFawks account for testing).
I would've guessed it's a networking issue, but why does a new account work then? Weird...

**Comment by Xijezu** [comment] 2018-07-24 20:00
Fixed with b1106b1.
Actually, this has always been an issue, but with the longer pause not working on the emulator we all totally forgot about it apparentely.

**Closed by Xijezu** 2018-07-24 20:00 UTC
Labels: bug, confirmed
