### ISSUE TITLE
suppoets for sorcerer class

### ISSUE THREAD

**Issue by petpowwer** [NGemity/RZEmulator#53] opened 2018-08-16 11:02 UTC
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 
buff the pet with a toggle
### Actual Behaviour
buffs the avatar with a  toggle
### Steps to reproduce the behaviour
make a sorcerer  you will see

**Comment by Xijezu** [comment] 2018-08-16 16:55
Duplicate of  #45

**Closed by Xijezu** 2018-08-16 16:55 UTC
