### ISSUE TITLE
broken class

### ISSUE THREAD

**Issue by petpowwer** [NGemity/RZEmulator#78] opened 2018-08-21 23:31 UTC
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 

summoner mastery makes pets stronger
### Actual Behaviour
does nothing
### Steps to reproduce the behaviour
make any class and learn the skill

**Comment by Xijezu** [comment] 2018-08-23 18:42
Duplicate of #52

**Closed by Xijezu** 2018-08-23 18:42 UTC
Labels: duplicate
