### ISSUE TITLE
pet class skills 

### ISSUE THREAD

**Issue by petpowwer** [NGemity/RZEmulator#44] opened 2018-08-15 10:24 UTC
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

**Comment by Xijezu** [comment] 2018-08-23 18:42
Duplicate of #52

**Closed by Xijezu** 2018-08-23 18:42 UTC
Labels: not implemented
